services:
  postgres:
    container_name: postgres_ctn
    image: postgres
    environment:
      POSTGRES_USER: ilham
      POSTGRES_PASSWORD: ilham
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ilham -d product"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aromapedia

  pgadmin:
    container_name: pgadmin_ctn
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@aziz.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - aromapedia

  product-service:
    build: ./product-service
    container_name: product_service_ctn
    ports:
      - "8081:8081"
    networks:
      - aromapedia
    depends_on:
      postgres:
        condition: service_healthy


networks:
  aromapedia:
    driver: bridge

volumes:
  postgres:
  pgadmin: