server:
  port: 8081

spring:
  application:
    name: product-service
    datasource:
      url: jdbc:postgresql://localhost:5432/product
      username: postgres
      password: postgres
    jpa:
      database: POSTGRESQL
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create-drop




